const KEY='josenga_one_company_os_v1';
const defaults={settings:{business:'JOSENGA',currency:'USD',whatsapp:'',email:''},leads:[{name:'Demo Prospect',company:'Local SME',value:1500,status:'New'}],clients:[],jobs:[],invoices:[],tasks:[{title:'Follow up new leads',done:false},{title:'Send today's quotations',done:false},{title:'Review outstanding invoices',done:false}]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:db.settings.currency||'USD',maximumFractionDigits:0}).format(Number(n)||0);
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function shell(title,sub,body,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p class="sub">${sub}</p></div><div class="actions">${actions}</div></div>${body}`}
function render(view='dashboard'){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const f={dashboard:dashboard,leads:leads,clients:clients,jobs:jobs,finance:finance,marketing:marketing,ai:ai,settings:settings}[view]||dashboard;$('#app').innerHTML=f();bind(view)}
function dashboard(){const pipeline=db.leads.reduce((s,l)=>s+(+l.value||0),0),paid=db.invoices.filter(x=>x.status==='Paid').reduce((s,x)=>s+(+x.amount||0),0),due=db.invoices.filter(x=>x.status!=='Paid').reduce((s,x)=>s+(+x.amount||0),0);return shell('Command Center','Your one-person business, operated from one screen.','<div class="hero"><h2>Turn conversations into revenue.</h2><p>JOSENGA connects leads, sales, clients, jobs, invoices, collections and AI decision support. Start with the pipeline, then execute the next money-making action.</p><div class="kpis"><span class="kpi">AI SALES</span><span class="kpi">CLIENTS</span><span class="kpi">JOBS</span><span class="kpi">CASH CONTROL</span></div></div><div class="grid"><div class="card metric"><div class="label">Pipeline value</div><div class="value">${money(pipeline)}</div><div class="hint">Active opportunities</div></div><div class="card metric"><div class="label">Cash collected</div><div class="value">${money(paid)}</div><div class="hint">Recorded as paid</div></div><div class="card metric"><div class="label">Outstanding</div><div class="value">${money(due)}</div><div class="hint">Needs follow-up</div></div><div class="card metric"><div class="label">Open jobs</div><div class="value">${db.jobs.filter(j=>j.status!=='Done').length}</div><div class="hint">Work in progress</div></div></div><div class="two"><div class="card"><div class="section-title">Today's execution queue</div>${db.tasks.map((t,i)=>`<label class="check"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}> ${t.title}</label>`).join('')}</div><div class="card"><div class="section-title">Revenue path</div><p>Lead → Quote → Job → Invoice → Payment → Reconcile → Profit</p><button class="btn gold" data-go="leads">Add revenue opportunity</button></div></div>')}
function leads(){return shell('Leads & Sales','Capture prospects and move them toward payment.','<div class="card"><div class="section-title">Add opportunity</div><form class="form" id="leadForm"><div class="field"><label>Prospect</label><input name="name" required placeholder="Contact name"></div><div class="field"><label>Company</label><input name="company" placeholder="Business"></div><div class="field"><label>Potential value</label><input name="value" type="number" min="0" placeholder="1500"></div><div class="field"><label>Stage</label><select name="status"><option>New</option><option>Qualified</option><option>Proposal</option><option>Won</option></select></div><div class="field full"><button class="btn primary">Add to pipeline</button></div></form></div><div class="card" style="margin-top:14px"><div class="section-title">Sales pipeline</div><div class="pipeline">${['New','Qualified','Proposal','Won'].map(s=>`<div class="stage"><h3>${s}</h3>${db.leads.filter(l=>l.status===s).map((l,i)=>`<div class="lead"><strong>${l.name}</strong><br>${l.company||''}<br><b>${money(l.value)}</b><br><button class="btn" data-leadwon="${db.leads.indexOf(l)}">${s==='Won'?'Won':'Mark Won'}</button></div>`).join('')||'<div class="empty">No leads</div>'}</div>`).join('')}</div></div>')}
function clients(){return shell('Clients','Your customer relationship base.','<div class="card"><div class="section-title">Client register</div><form class="form" id="clientForm"><div class="field"><label>Client</label><input name="name" required></div><div class="field"><label>Company</label><input name="company"></div><div class="field"><label>Phone / WhatsApp</label><input name="phone"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field full"><button class="btn primary">Save client</button></div></form></div><div class="card" style="margin-top:14px"><table class="table"><thead><tr><th>Client</th><th>Company</th><th>Contact</th></tr></thead><tbody>${db.clients.map(c=>`<tr><td>${c.name}</td><td>${c.company||''}</td><td>${c.phone||c.email||''}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No clients yet.</td></tr>'}</tbody></table></div>')}
function jobs(){return shell('Jobs','Deliver work without losing track of commitments.','<div class="card"><form class="form" id="jobForm"><div class="field"><label>Job / project</label><input name="title" required></div><div class="field"><label>Client</label><input name="client"></div><div class="field"><label>Value</label><input name="value" type="number"></div><div class="field"><label>Status</label><select name="status"><option>Open</option><option>In Progress</option><option>Done</option></select></div><div class="field full"><button class="btn primary">Create job</button></div></form></div><div class="card" style="margin-top:14px"><table class="table"><thead><tr><th>Job</th><th>Client</th><th>Value</th><th>Status</th></tr></thead><tbody>${db.jobs.map(j=>`<tr><td>${j.title}</td><td>${j.client||''}</td><td>${money(j.value)}</td><td><span class="badge ${j.status==='Done'?'green':'gold'}">${j.status}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No jobs yet.</td></tr>'}</tbody></table></div>')}
function finance(){const total=db.invoices.reduce((s,x)=>s+(+x.amount||0),0);return shell('Invoices & Cash','Create invoices, record payments and expose cash that needs attention.','<div class="grid"><div class="card metric"><div class="label">Invoiced</div><div class="value">'+money(total)+'</div></div><div class="card metric"><div class="label">Paid</div><div class="value">'+money(db.invoices.filter(x=>x.status==='Paid').reduce((s,x)=>s+(+x.amount||0),0))+'</div></div><div class="card metric"><div class="label">Due</div><div class="value">'+money(db.invoices.filter(x=>x.status!=='Paid').reduce((s,x)=>s+(+x.amount||0),0))+'</div></div><div class="card metric"><div class="label">Control</div><div class="value">AI → Approve</div></div></div><div class="card" style="margin-top:14px"><div class="section-title">Create invoice</div><form class="form" id="invoiceForm"><div class="field"><label>Client</label><input name="client" required></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0" required></div><div class="field"><label>Status</label><select name="status"><option>Due</option><option>Paid</option></select></div><div class="field"><label>Reference</label><input name="ref" placeholder="INV-001"></div><div class="field full"><button class="btn primary">Record invoice</button></div></form></div><div class="card" style="margin-top:14px"><table class="table"><thead><tr><th>Reference</th><th>Client</th><th>Amount</th><th>Status</th></tr></thead><tbody>${db.invoices.map(x=>`<tr><td>${x.ref||'—'}</td><td>${x.client}</td><td>${money(x.amount)}</td><td><span class="badge ${x.status==='Paid'?'green':'red'}">${x.status}</span></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No invoices yet.</td></tr>'}</tbody></table></div>')}
function marketing(){return shell('Marketing Engine','Use one offer repeatedly until it produces measurable leads.','<div class="two"><div class="card"><div class="section-title">Revenue offer builder</div><form class="form" id="marketingForm"><div class="field full"><label>What do you sell?</label><input name="offer" placeholder="AI business automation"></div><div class="field"><label>Target customer</label><input name="audience" placeholder="SMEs in Lusaka"></div><div class="field"><label>Main result</label><input name="result" placeholder="save time and win customers"></div><div class="field full"><button class="btn gold">Generate campaign brief</button></div></form></div><div class="card"><div class="section-title">Campaign output</div><div id="campaignOutput" class="empty">Enter an offer to generate a ready-to-use campaign brief.</div></div></div>')}
function ai(){return shell('AI Business Advisor','Use ChatGPT as the intelligence layer; keep sensitive actions under owner approval.','<div class="card"><div class="section-title">Ask the business advisor</div><textarea id="aiq" placeholder="Example: Which activity should I do first today to increase cash collected?"></textarea><div class="actions" style="margin-top:10px"><button class="btn primary" id="aiBtn">Prepare AI instruction</button><button class="btn" id="chatgptBtn">Open ChatGPT</button></div><div id="aiout" style="margin-top:14px"></div></div><div class="two"><div class="card"><div class="section-title">AI workforce</div><p>CEO • Sales • Marketing • Admin • Finance • Research • Operations • Cybersecurity</p></div><div class="card"><div class="section-title">Control rule</div><p>AI prepares and verifies. You approve sensitive actions. The system records the decision and result.</p></div></div>')}
function settings(){return shell('Settings','Configure the revenue identity of your one-person company.','<div class="card"><form class="form" id="settingsForm"><div class="field"><label>Business name</label><input name="business" value="'+(db.settings.business||'')+'"></div><div class="field"><label>Currency</label><select name="currency"><option '+(db.settings.currency==='USD'?'selected':'')+'>USD</option><option '+(db.settings.currency==='ZMW'?'selected':'')+'>ZMW</option><option '+(db.settings.currency==='GBP'?'selected':'')+'>GBP</option><option '+(db.settings.currency==='EUR'?'selected':'')+'>EUR</option></select></div><div class="field"><label>WhatsApp number</label><input name="whatsapp" value="'+(db.settings.whatsapp||'')+'" placeholder="Country code + number"></div><div class="field"><label>Business email</label><input name="email" value="'+(db.settings.email||'')+'"></div><div class="field full"><button class="btn primary">Save settings</button><button type="button" class="btn danger" id="resetBtn">Reset demo data</button></div></form></div>')}
function bind(view){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{render(b.dataset.view);if(innerWidth<601)$('#sidebar').classList.remove('open')});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>render(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
 document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{db.tasks[+x.dataset.task].done=x.checked;save()});
 const lf=$('#leadForm');if(lf)lf.onsubmit=e=>{e.preventDefault();const f=new FormData(lf);db.leads.push(Object.fromEntries(f));save();toast('Opportunity added');render('leads')};
 document.querySelectorAll('[data-leadwon]').forEach(b=>b.onclick=()=>{db.leads[+b.dataset.leadwon].status='Won';save();render('leads');toast('Lead marked Won')});
 const cf=$('#clientForm');if(cf)cf.onsubmit=e=>{e.preventDefault();db.clients.push(Object.fromEntries(new FormData(cf)));save();toast('Client saved');render('clients')};
 const jf=$('#jobForm');if(jf)jf.onsubmit=e=>{e.preventDefault();db.jobs.push(Object.fromEntries(new FormData(jf)));save();toast('Job created');render('jobs')};
 const inf=$('#invoiceForm');if(inf)inf.onsubmit=e=>{e.preventDefault();db.invoices.push(Object.fromEntries(new FormData(inf)));save();toast('Invoice recorded');render('finance')};
 const mf=$('#marketingForm');if(mf)mf.onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(mf));$('#campaignOutput').innerHTML=`<p><strong>Offer:</strong> ${f.offer}</p><p><strong>Audience:</strong> ${f.audience}</p><p><strong>Promise:</strong> ${f.result}</p><p><strong>CTA:</strong> Book a free 15-minute business audit.</p><p><strong>Channel:</strong> WhatsApp + LinkedIn + Facebook + direct outreach.</p>`};
 const ab=$('#aiBtn');if(ab)ab.onclick=()=>{const q=$('#aiq').value.trim()||'What is the highest-value action I should take today?';const context=`You are the JOSENGA Business Advisor. Business: ${db.settings.business}. Pipeline: ${money(db.leads.reduce((s,l)=>s+(+l.value||0),0))}. Outstanding invoices: ${money(db.invoices.filter(x=>x.status!=='Paid').reduce((s,x)=>s+(+x.amount||0),0))}. Open jobs: ${db.jobs.filter(j=>j.status!=='Done').length}. User question: ${q}. Give 3 practical actions ranked by expected revenue impact, with the first action executable today.`;$('#aiout').innerHTML=`<div class="card" style="background:#f8f6f0"><strong>Copy this instruction into ChatGPT:</strong><textarea style="width:100%;margin-top:8px;min-height:180px" readonly>${context}</textarea><button class="btn" id="copyAI">Copy instruction</button></div>`;$('#copyAI').onclick=()=>navigator.clipboard?.writeText(context).then(()=>toast('Instruction copied'))};
 const cg=$('#chatgptBtn');if(cg)cg.onclick=()=>window.open('https://chatgpt.com/','_blank');
 const sf=$('#settingsForm');if(sf)sf.onsubmit=e=>{e.preventDefault();db.settings={...db.settings,...Object.fromEntries(new FormData(sf))};save();toast('Settings saved');render('settings')};const rb=$('#resetBtn');if(rb)rb.onclick=()=>{if(confirm('Reset JOSENGA demo data?')){db=JSON.parse(JSON.stringify(defaults));save();render('dashboard')}};
}
render('dashboard');
